apiVersion: apps/v1
kind: Deployment
metadata:
    annotations:
        sidecar.jaegertracing.io/inject: 'true'
    labels:
        app: minitiktok-user-http
    name: minitiktok-user-http
    namespace: minitiktok-user-http
spec:
    selector:
        matchLabels:
            name: minitiktok-user-http
    template:
        metadata:
            labels:
                app: minitiktok-user-http
                branch: dev
                version: ${BUILD_NUMBER}-${CI_COMMIT_ID}
                name: minitiktok-user-http
                dream-app: minitiktok-user-http
                dream-unit: minitiktok-user-http
        spec:
            imagePullSecrets:
                -   name: regcred
            containers:
                -   image: ${IMAGE}
                    imagePullPolicy: IfNotPresent
                    name: minitiktok-user-http
                    readinessProbe:
                        httpGet:
                            path: /health_check
                            port: 14514
                        initialDelaySeconds: 5
                        periodSeconds: 5
                        successThreshold: 2
                    livenessProbe:
                        failureThreshold: 3
                        httpGet:
                            path: /health_check
                            port: 14514
                        initialDelaySeconds: 10
                        periodSeconds: 10
                        timeoutSeconds: 1
                    envFrom:
                        -   configMapRef:
                                name: env-config
                        -   configMapRef:
                                name: config
                    ports:
                        -   containerPort: 14514
            terminationGracePeriodSeconds: 30
