apiVersion: v1
kind: Service
metadata:
    name: minitiktok-user-http
    namespace: minitiktok-user-http
spec:
    ports:
        -   name: http
            port: 14514
            protocol: TCP
            targetPort: 14514
    selector:
        name: minitiktok-user-http
        branch: dev
    type: ClusterIP